name: Build and upload pair_tool

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]
    workflow_dispatch:

env:
    CARGO_TERM_COLOR: always

jobs:
    build-linux:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Install dependencies
              run: sudo apt update && sudo apt install libgtk-3-dev pkg-config -y
            - name: Build
              run: |
                cargo build --target x86_64-unknown-linux-gnu --release
                chmod +x target/x86_64-unknown-linux-gnu/release/pair_tool
            - name: Upload Artifact
              uses: actions/upload-artifact@v3.1.1
              with:
                  name: pair_tool-linux
                  path: target/x86_64-unknown-linux-gnu/release/pair_tool

    # build-arm:
    #     env:
    #         CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF_LINKER: arm-linux-gnueabihf-gcc
    #         PKG_CONFIG_ALLOW_CROSS: 1
    #         PKG_CONFIG_PATH: /usr/lib/arm-linux-gnueabihf/pkgconfig/

    #     runs-on: ubuntu-latest

    #     steps:
    #         - uses: actions/checkout@v3
    #         - name: Add architecture
    #           run: sudo dpkg --add-architecture armhf
    #         - name: Update && upgrade
    #           continue-on-error: true
    #           run: sudo apt update && apt upgrade -y
    #         - name: Install dependencies
    #           run: sudo apt install gcc-arm-linux-gnueabihf libgtk-3-dev:armhf pkg-config build-essential checkinstall git autoconf automake libtool-bin -y
    #         - name: Add target
    #           run: rustup target add armv7-unknown-linux-gnueabihf
    #         - name: Build
    #           run: cargo build --release --target=armv7-unknown-linux-gnueabihf
    #         - name: Move binary
    #           run: mv target/armv7-unknown-linux-gnueabihf/release/pair_tool armv7-pair_tool
    #         - name: Upload artifact
    #           uses: actions/upload-artifact@v3.1.0
    #           with:
    #               # A file, directory or wildcard pattern that describes what to upload
    #               path: armv7-pair_tool
#     build-windows:
#         runs-on: ubuntu-latest
        
#         steps:
#             - uses: actions/checkout@v3
#             - name: Install cross
#               run: cargo install cross
#             - name: Build for Windows
#               run: cross build -r --target x86_64-pc-windows-gnu
#             - name: Upload Windows
#               uses: actions/upload-artifact@v3.1.1
#               with:
#                   name: pair_tool_windows
#                   path: /target/x86_64-pc-windows-gnu/release/pair_tool.exe
                  
    build-macos-windows:
        runs-on: macos-latest

        steps:
            - uses: actions/checkout@v3
            - name: Install Dependencies
              run: brew install automake autoconf libtool git pkg-config mingw-w64
            - name: Build
              run: |
                rustup target add x86_64-pc-windows-gnu
                cargo build --release
                cargo build --release --target x86_64-pc-windows-gnu
                chmod +x target/release/pair_tool
            - name: Upload Artifact
              uses: actions/upload-artifact@v3.1.1
              with:
                  name: pair_tool-macos
                  path: target/release/pair_tool
                  
            - name: Upload Windows
              uses: actions/upload-artifact@v3.1.1
              with:
                  name: pair_tool-windows
                  path: target/x86_64-pc-windows-gnu/release/pair_tool.exe
